import { PHONEMES } from "@/data/phonemes";
import { safeJsonForScript } from "./safeJsonForScript.js";

export function wordsearchTemplate(config) {
  const body = `
<header class="page-header">
  <p class="eyebrow">Phoneme'le</p>
  <h1>Phoneme Word Search</h1>
</header>
<main>
  <div id="status" class="status" aria-live="polite"></div>
  <div id="wordlist" class="ws-wordlist"></div>
  <div id="grid" class="ws-grid" role="group" aria-label="Word search grid"></div>
</main>
<footer class="page-footer">
  <p>Generated by Phoneme'le.</p>
</footer>`;

  const script = `
(function () {
  "use strict";
  var PHONEMES = ${safeJsonForScript(PHONEMES)};
  var CONFIG = ${safeJsonForScript(config)};

  function bySymbol(sym) {
    for (var i = 0; i < PHONEMES.length; i++) {
      if (PHONEMES[i].symbol === sym) return PHONEMES[i];
    }
    return null;
  }
  function hintFor(sym) {
    var p = bySymbol(sym);
    return p.label + " (as in " + p.example + ")";
  }
  function formatPhoneme(sym) {
    return "/" + sym + "/";
  }
  function formatPhonemeWord(word) {
    return "/" + word.join(" ") + "/";
  }
  function describePhoneme(sym) {
    return "Phoneme " + formatPhoneme(sym) + ": " + hintFor(sym);
  }

  var foundIndices = [];
  var selectionStart = null;

  var gridEl = document.getElementById("grid");
  var wordlistEl = document.getElementById("wordlist");
  var statusEl = document.getElementById("status");

  function placementCells(p) {
    var cells = [];
    for (var i = 0; i < p.word.length; i++) {
      cells.push({ row: p.row + p.dy * i, col: p.col + p.dx * i });
    }
    return cells;
  }

  function cellsMatchPlacement(start, end, p) {
    var cells = placementCells(p);
    var first = cells[0];
    var last = cells[cells.length - 1];
    var forward =
      start.row === first.row && start.col === first.col &&
      end.row === last.row && end.col === last.col;
    var backward =
      start.row === last.row && start.col === last.col &&
      end.row === first.row && end.col === first.col;
    return forward || backward;
  }

  function foundCellKeySet() {
    var set = {};
    foundIndices.forEach(function (index) {
      placementCells(CONFIG.placements[index]).forEach(function (cell) {
        set[cell.row + "," + cell.col] = true;
      });
    });
    return set;
  }

  function renderWordList() {
    wordlistEl.innerHTML = "";
    var ul = document.createElement("ul");
    ul.className = "ws-word-items";
    CONFIG.placements.forEach(function (p, index) {
      var li = document.createElement("li");
      li.className = "ws-word" + (foundIndices.indexOf(index) !== -1 ? " found" : "");
      li.textContent = formatPhonemeWord(p.word);
      ul.appendChild(li);
    });
    wordlistEl.appendChild(ul);
  }

  function renderStatus() {
    var total = CONFIG.placements.length;
    statusEl.textContent =
      foundIndices.length + " of " + total + " words found" +
      (total > 0 && foundIndices.length === total ? " \\u2014 all words found!" : "");
  }

  function renderGrid() {
    gridEl.innerHTML = "";
    gridEl.style.setProperty("--ws-size", CONFIG.grid.length);
    var foundSet = foundCellKeySet();
    CONFIG.grid.forEach(function (row, r) {
      row.forEach(function (symbol, c) {
        var p = bySymbol(symbol);
        var btn = document.createElement("button");
        btn.type = "button";
        var className = "ws-cell";
        if (selectionStart && selectionStart.row === r && selectionStart.col === c) {
          className += " selected";
        }
        var isFound = !!foundSet[r + "," + c];
        if (isFound) className += " found";
        btn.className = className;
        btn.textContent = p.symbol;
        btn.title = hintFor(symbol);
        btn.setAttribute("aria-label", describePhoneme(symbol));
        btn.setAttribute("aria-pressed", isFound ? "true" : "false");
        btn.addEventListener("click", function () {
          handleCellClick(r, c);
        });
        gridEl.appendChild(btn);
      });
    });
  }

  function handleCellClick(row, col) {
    if (!selectionStart) {
      selectionStart = { row: row, col: col };
      renderGrid();
      return;
    }
    var end = { row: row, col: col };
    var matchIndex = -1;
    for (var i = 0; i < CONFIG.placements.length; i++) {
      if (foundIndices.indexOf(i) !== -1) continue;
      if (cellsMatchPlacement(selectionStart, end, CONFIG.placements[i])) {
        matchIndex = i;
        break;
      }
    }
    if (matchIndex !== -1) {
      foundIndices.push(matchIndex);
    }
    selectionStart = null;
    update();
  }

  function update() {
    renderGrid();
    renderWordList();
    renderStatus();
  }

  update();
})();`;

  return { body, script };
}
