import { PHONEMES, KEYBOARD_ROWS } from "@/data/phonemes";
import { safeJsonForScript } from "./safeJsonForScript.js";

export function wordleTemplate(config) {
  const body = `
<header class="page-header">
  <p class="eyebrow">Phoneme'le</p>
  <h1>Phoneme Wordle</h1>
</header>
<main>
  <div id="status" class="status" aria-live="polite"></div>
  <div id="grid" class="grid" role="table" aria-label="Wordle guesses"></div>
  <div id="guess-word" class="guess-word"></div>
  <div class="actions">
    <button type="button" id="backspace-btn" class="action-button">Backspace</button>
    <button type="button" id="clear-btn" class="action-button">Clear</button>
    <button type="button" id="submit-btn" class="action-button primary">Submit guess</button>
    <button type="button" id="reset-btn" class="action-button" hidden>Try again</button>
  </div>
  <div id="keyboard" class="keyboard" role="group" aria-label="Phoneme keyboard"></div>
</main>
<footer class="page-footer">
  <p>Generated by Phoneme'le.</p>
</footer>`;

  const script = `
(function () {
  "use strict";
  var PHONEMES = ${safeJsonForScript(PHONEMES)};
  var KEYBOARD_ROWS = ${safeJsonForScript(KEYBOARD_ROWS)};
  var CONFIG = ${safeJsonForScript(config)};
  if (CONFIG.title) document.querySelector(".page-header h1").textContent = CONFIG.title;

  function bySymbol(sym) {
    for (var i = 0; i < PHONEMES.length; i++) {
      if (PHONEMES[i].symbol === sym) return PHONEMES[i];
    }
    return null;
  }
  function hintFor(sym) {
    var p = bySymbol(sym);
    return p.label + " (as in " + p.example + ")";
  }
  function formatPhoneme(sym) {
    return "/" + sym + "/";
  }
  function formatPhonemeWord(word) {
    return "/" + word.join(" ") + "/";
  }
  function describePhoneme(sym) {
    return "Phoneme " + formatPhoneme(sym) + ": " + hintFor(sym);
  }

  function scoreGuess(guess, answer) {
    var result = new Array(guess.length).fill("absent");
    var consumed = new Array(answer.length).fill(false);
    var i, j;
    for (i = 0; i < guess.length; i++) {
      if (guess[i] === answer[i]) {
        result[i] = "correct";
        consumed[i] = true;
      }
    }
    for (i = 0; i < guess.length; i++) {
      if (result[i] === "correct") continue;
      var matchIndex = -1;
      for (j = 0; j < answer.length; j++) {
        if (!consumed[j] && answer[j] === guess[i]) {
          matchIndex = j;
          break;
        }
      }
      if (matchIndex !== -1) {
        result[i] = "present";
        consumed[matchIndex] = true;
      }
    }
    return result;
  }
  function isWin(scores) {
    return scores.every(function (s) { return s === "correct"; });
  }
  function stateLabel(s) {
    if (s === "correct") return "correct position";
    if (s === "present") return "present, wrong position";
    return "not in word";
  }
  function stateIcon(s) {
    if (s === "correct") return "\\u2713";
    if (s === "present") return "\\u25c6";
    return "\\u2715";
  }

  var state = { currentGuess: [], submittedGuesses: [], scores: [] };

  var gridEl = document.getElementById("grid");
  var statusEl = document.getElementById("status");
  var guessWordEl = document.getElementById("guess-word");
  var keyboardEl = document.getElementById("keyboard");
  var backspaceBtn = document.getElementById("backspace-btn");
  var clearBtn = document.getElementById("clear-btn");
  var submitBtn = document.getElementById("submit-btn");
  var resetBtn = document.getElementById("reset-btn");

  function isGameOver() {
    return state.scores.some(isWin) || state.submittedGuesses.length >= CONFIG.maxGuesses;
  }

  function renderGrid() {
    gridEl.innerHTML = "";
    for (var r = 0; r < CONFIG.maxGuesses; r++) {
      var row = document.createElement("div");
      row.className = "row";
      row.setAttribute("role", "row");
      var guess = state.submittedGuesses[r];
      var scores = guess ? state.scores[r] : null;
      for (var c = 0; c < CONFIG.answer.length; c++) {
        var symbol = guess ? guess[c] : null;
        var cellState = scores ? scores[c] : null;
        var cell = document.createElement("div");
        cell.className = "tile" + (cellState ? " " + cellState : "");
        cell.setAttribute("role", "cell");
        if (symbol) {
          var p = bySymbol(symbol);
          cell.setAttribute(
            "aria-label",
            cellState ? describePhoneme(symbol) + ", " + stateLabel(cellState) : describePhoneme(symbol)
          );
          cell.title = hintFor(symbol);
          if (cellState) {
            var icon = document.createElement("span");
            icon.className = "icon";
            icon.setAttribute("aria-hidden", "true");
            icon.textContent = stateIcon(cellState);
            cell.appendChild(icon);
          }
          var labelSpan = document.createElement("span");
          labelSpan.className = "label";
          labelSpan.textContent = p.symbol;
          cell.appendChild(labelSpan);
        } else {
          cell.setAttribute("aria-label", "empty");
        }
        row.appendChild(cell);
      }
      gridEl.appendChild(row);
    }
  }

  function renderGuessWord() {
    guessWordEl.innerHTML = "";
    if (state.currentGuess.length === 0) {
      var empty = document.createElement("p");
      empty.className = "empty";
      empty.textContent = "Click phonemes below to build your guess";
      guessWordEl.appendChild(empty);
      return;
    }
    var transcription = document.createElement("div");
    transcription.className = "transcription";
    transcription.setAttribute(
      "aria-label",
      "Current phoneme guess " + formatPhonemeWord(state.currentGuess)
    );
    var openingSlash = document.createElement("span");
    openingSlash.className = "slash";
    openingSlash.setAttribute("aria-hidden", "true");
    openingSlash.textContent = "/";
    transcription.appendChild(openingSlash);
    var ul = document.createElement("ul");
    ul.className = "chips";
    state.currentGuess.forEach(function (symbol, index) {
      var p = bySymbol(symbol);
      var li = document.createElement("li");
      var btn = document.createElement("button");
      btn.type = "button";
      btn.className = "chip";
      btn.textContent = p.symbol;
      btn.title = hintFor(symbol);
      btn.setAttribute("aria-label", "Remove " + describePhoneme(symbol));
      btn.addEventListener("click", function () {
        state.currentGuess.splice(index, 1);
        update();
      });
      li.appendChild(btn);
      ul.appendChild(li);
    });
    transcription.appendChild(ul);
    var closingSlash = document.createElement("span");
    closingSlash.className = "slash";
    closingSlash.setAttribute("aria-hidden", "true");
    closingSlash.textContent = "/";
    transcription.appendChild(closingSlash);
    guessWordEl.appendChild(transcription);
  }

  function renderKeyboard() {
    if (keyboardEl.childElementCount > 0) return;
    KEYBOARD_ROWS.forEach(function (row) {
      var rowEl = document.createElement("div");
      rowEl.className = "kb-row";
      var title = document.createElement("h3");
      title.className = "kb-row-title";
      title.textContent = row.title;
      rowEl.appendChild(title);
      var buttons = document.createElement("div");
      buttons.className = "kb-row-buttons";
      row.symbols.forEach(function (symbol) {
        var p = bySymbol(symbol);
        var wrapper = document.createElement("span");
        wrapper.className = "kb-wrapper";
        var btn = document.createElement("button");
        btn.type = "button";
        btn.className = "kb-button";
        btn.textContent = formatPhoneme(symbol);
        btn.setAttribute("aria-label", "Phoneme " + formatPhoneme(symbol));
        if (CONFIG.showHints) {
          var hintId = "hint-" + encodeURIComponent(symbol);
          btn.setAttribute("aria-describedby", hintId);
          btn.title = hintFor(symbol);
        }
        btn.addEventListener("click", function () {
          if (isGameOver()) return;
          if (state.currentGuess.length >= CONFIG.answer.length) return;
          state.currentGuess.push(symbol);
          update();
        });
        wrapper.appendChild(btn);
        if (CONFIG.showHints) {
          var hint = document.createElement("span");
          hint.className = "kb-hint";
          hint.id = "hint-" + encodeURIComponent(symbol);
          hint.textContent = hintFor(symbol);
          wrapper.appendChild(hint);
        }
        buttons.appendChild(wrapper);
      });
      rowEl.appendChild(buttons);
      keyboardEl.appendChild(rowEl);
    });
  }

  function renderStatus() {
    var won = state.scores.some(isWin);
    var lost = !won && state.submittedGuesses.length >= CONFIG.maxGuesses;
    statusEl.innerHTML = "";
    if (won || lost) {
      var result = document.createElement("div");
      result.className = "result";
      var p1 = document.createElement("p");
      p1.textContent = won ? "Solved!" : "Out of guesses.";
      var phonemeResult = document.createElement("p");
      phonemeResult.textContent = "Phoneme word: ";
      var phonemeStrong = document.createElement("strong");
      phonemeStrong.textContent = formatPhonemeWord(CONFIG.answer);
      phonemeResult.appendChild(phonemeStrong);
      var p2 = document.createElement("p");
      p2.textContent = "English word: ";
      var strong = document.createElement("strong");
      strong.textContent = CONFIG.englishWord || "(not set)";
      p2.appendChild(strong);
      result.appendChild(p1);
      result.appendChild(phonemeResult);
      result.appendChild(p2);
      statusEl.appendChild(result);
      resetBtn.hidden = false;
      keyboardEl.hidden = true;
      guessWordEl.hidden = true;
      submitBtn.hidden = true;
      backspaceBtn.hidden = true;
      clearBtn.hidden = true;
    } else {
      var attemptsLeft = CONFIG.maxGuesses - state.submittedGuesses.length;
      var p = document.createElement("p");
      p.className = "attempts";
      p.textContent =
        attemptsLeft + " guess" + (attemptsLeft === 1 ? "" : "es") + " left" +
        " \\u2014 guess needs " + CONFIG.answer.length + " phonemes (currently " +
        state.currentGuess.length + ")";
      statusEl.appendChild(p);
      if (CONFIG.showHints && CONFIG.hint) {
        var clue = document.createElement("p");
        clue.textContent = "Hint: " + CONFIG.hint;
        statusEl.appendChild(clue);
      }
      resetBtn.hidden = true;
      keyboardEl.hidden = false;
      guessWordEl.hidden = false;
      submitBtn.hidden = false;
      backspaceBtn.hidden = false;
      clearBtn.hidden = false;
      submitBtn.disabled = state.currentGuess.length !== CONFIG.answer.length;
      backspaceBtn.disabled = state.currentGuess.length === 0;
      clearBtn.disabled = state.currentGuess.length === 0;
    }
  }

  function update() {
    renderGrid();
    renderGuessWord();
    renderStatus();
  }

  backspaceBtn.addEventListener("click", function () {
    state.currentGuess.pop();
    update();
  });
  clearBtn.addEventListener("click", function () {
    state.currentGuess = [];
    update();
  });
  submitBtn.addEventListener("click", function () {
    if (state.currentGuess.length !== CONFIG.answer.length || isGameOver()) return;
    state.submittedGuesses.push(state.currentGuess);
    state.scores.push(scoreGuess(state.currentGuess, CONFIG.answer));
    state.currentGuess = [];
    update();
  });
  resetBtn.addEventListener("click", function () {
    state.currentGuess = [];
    state.submittedGuesses = [];
    state.scores = [];
    update();
  });

  renderKeyboard();
  update();
})();`;

  return { body, script };
}
